CREATE TABLE USUARIOS(
  ID_U NUMBER(20) CONSTRAINT USUARIOS_PK PRIMARY KEY ,
  USUARIO VARCHAR2(30) CONSTRAINT USUARIOS_UK1 UNIQUE
                        CONSTRAINT USUARIOS_NN1 NOT NULL ,
  E_MAIL VARCHAR2(60) CONSTRAINT USUARIOS_UK2 UNIQUE
                        CONSTRAINT USUARIOS_NN2 NOT NULL ,
  NOMBRE VARCHAR2(30) CONSTRAINT USUARIOS_NN3 NOT NULL ,
  APELLIDO1 VARCHAR2(30) CONSTRAINT USUARIOS_NN4 NOT NULL ,
  APELLIDO2 VARCHAR2(30),
  PASSW VARCHAR2(100) CONSTRAINT USUARIOS_NN5 NOT NULL
);
CREATE TABLE POST(
  ID_U NUMBER(20) CONSTRAINT POST_FK1 REFERENCES USUARIOS(ID_U) ON DELETE CASCADE
                    CONSTRAINT POST_NN2 NOT NULL ,
  PID NUMBER(20) CONSTRAINT POST_PK PRIMARY KEY ,
  TEXTO VARCHAR2(1000) CONSTRAINT POST_NN1 NOT NULL ,
  PID_REL NUMBER(20) CONSTRAINT POST_FK2 REFERENCES POST(PID) ON DELETE SET NULL,
  PUBLICACION DATE CONSTRAINT POST_NN3 NOT NULL
                    CONSTRAINT POST_CK1 CHECK (PUBLICACION>TO_DATE('2/2/2017','DD/MM/YYYY')),
  DURACION INTERVAL DAY TO SECOND CONSTRAINT POST_NN4 NOT NULL
);
CREATE TABLE CONTACTOS (
  ID_U NUMBER(20) CONSTRAINT CONTACTOS_FK1 REFERENCES USUARIOS(ID_U)ON DELETE CASCADE,
  CONTACTO NUMBER(20) CONSTRAINT CONTACTOS_FK2 REFERENCES USUARIOS(ID_U) ON DELETE CASCADE,
  CONSTRAINT CONTACTOS_PK PRIMARY KEY (ID_U, CONTACTO)
);

ALTER TABLE CONTACTOS ADD CONSTRAINT CONTACTOS_CK1 CHECK (ID_U!=CONTACTO);

CREATE TABLE SER_VISIBLE(
  ID_U NUMBER(20),
  CONTACTO NUMBER(20),
  PID NUMBER(20) CONSTRAINT SER_VISIBLE_FK2 REFERENCES POST(PID) ON DELETE CASCADE,
  CONSTRAINT SER_VISIBLE_FK1 FOREIGN KEY (ID_U, CONTACTO) REFERENCES CONTACTOS(ID_U, CONTACTO),
  CONSTRAINT SER_VISIBLE_PK PRIMARY KEY (ID_U, CONTACTO, PID)
);

ALTER TABLE POST ADD CONSTRAINT POST_CK2 CHECK (DURACION<INTERVAL '30' MINUTE);

RENAME SER_VISIBLE TO COMPARTIR;

ALTER  TABLE USUARIOS RENAME CONSTRAINT USUARIOS_PK TO SUPERCLAVE;

ALTER TABLE POST MODIFY (PUBLICACION DEFAULT SYSDATE);

ALTER TABLE USUARIOS DISABLE CONSTRAINT USUARIOS_NN5;

ALTER TABLE POST ADD(
  VISIBLE CHAR(2) DEFAULT 'SI' CONSTRAINT POST_CK3 CHECK (VISIBLE='SI'OR VISIBLE='NO')
);

INSERT INTO USUARIOS (ID_U, USUARIO, E_MAIL, NOMBRE, APELLIDO1,APELLIDO2)
  VALUES (4,'sercal','sercal1980@gmail.com','Francisco','Serrano','Calvo');

INSERT INTO POST (ID_U, TEXTO, PUBLICACION, DURACION)
  VALUES (2,'Hola','6/2/2017','7');

commit ;

ALTER TABLE USUARIOS MODIFY (PASSW DEFAULT '12345');

UPDATE USUARIOS SET E_MAIL='superlourdes@gmail.com' WHERE E_MAIL='lurdita@bbc.co.uk';

DELETE FROM USUARIOS WHERE USUARIO='ramongar';

